version: "3.8"
services:
  app:
    build:
      # context can/may/will be different per-project setup
      context: .
      dockerfile: Dockerfile
      target: builder
      args:
        - user={user_name}
        - personal_access_token=personal_access_token
    ports:
      - "8000:8000"
      - "8090:8090"
    command: "./main"
  redis:
    image: redis:6.0.8-alpine
    ports:
      - "6379:6379"
  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - "8092:8080"
    volumes:
      - ./pb/:/api
    environment:
      SWAGGER_JSON: /api/confession.swagger.json
      BASE_URL: /swagger
