// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/confession.proto

package confessionroom

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_dcb3f0e195a3d881, []int{0}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type HealthCheckReply struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HealthCheckReply) Reset()         { *m = HealthCheckReply{} }
func (m *HealthCheckReply) String() string { return proto.CompactTextString(m) }
func (*HealthCheckReply) ProtoMessage()    {}
func (*HealthCheckReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_dcb3f0e195a3d881, []int{1}
}

func (m *HealthCheckReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HealthCheckReply.Unmarshal(m, b)
}
func (m *HealthCheckReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HealthCheckReply.Marshal(b, m, deterministic)
}
func (m *HealthCheckReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HealthCheckReply.Merge(m, src)
}
func (m *HealthCheckReply) XXX_Size() int {
	return xxx_messageInfo_HealthCheckReply.Size(m)
}
func (m *HealthCheckReply) XXX_DiscardUnknown() {
	xxx_messageInfo_HealthCheckReply.DiscardUnknown(m)
}

var xxx_messageInfo_HealthCheckReply proto.InternalMessageInfo

func (m *HealthCheckReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*Empty)(nil), "confessionroom.Empty")
	proto.RegisterType((*HealthCheckReply)(nil), "confessionroom.HealthCheckReply")
}

func init() { proto.RegisterFile("pb/confession.proto", fileDescriptor_dcb3f0e195a3d881) }

var fileDescriptor_dcb3f0e195a3d881 = []byte{
	// 180 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2e, 0x48, 0xd2, 0x4f,
	0xce, 0xcf, 0x4b, 0x4b, 0x2d, 0x2e, 0xce, 0xcc, 0xcf, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17,
	0xe2, 0x43, 0x88, 0x14, 0xe5, 0xe7, 0xe7, 0x4a, 0xc9, 0xa4, 0xe7, 0xe7, 0xa7, 0xe7, 0xa4, 0xea,
	0x27, 0x16, 0x64, 0xea, 0x27, 0xe6, 0xe5, 0xe5, 0x97, 0x24, 0x96, 0x64, 0xe6, 0xe7, 0x15, 0x43,
	0x54, 0x2b, 0xb1, 0x73, 0xb1, 0xba, 0xe6, 0x16, 0x94, 0x54, 0x2a, 0xe9, 0x70, 0x09, 0x78, 0xa4,
	0x26, 0xe6, 0x94, 0x64, 0x38, 0x67, 0xa4, 0x26, 0x67, 0x07, 0xa5, 0x16, 0xe4, 0x54, 0x0a, 0x49,
	0x70, 0xb1, 0xe7, 0xa6, 0x16, 0x17, 0x27, 0xa6, 0xa7, 0x4a, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06,
	0xc1, 0xb8, 0x46, 0xf9, 0x5c, 0x5c, 0xce, 0x70, 0x6b, 0x84, 0x12, 0xb9, 0xb8, 0x91, 0xf4, 0x0a,
	0x89, 0xea, 0xa1, 0x3a, 0x41, 0x0f, 0x6c, 0x83, 0x94, 0x02, 0xba, 0x30, 0xba, 0x7d, 0x4a, 0x92,
	0x4d, 0x97, 0x9f, 0x4c, 0x66, 0x12, 0x16, 0x12, 0x04, 0x3b, 0x36, 0x03, 0x2c, 0x1d, 0x9f, 0x0c,
	0x92, 0x4f, 0x62, 0x03, 0x3b, 0xd7, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x63, 0x37, 0x8d, 0x2f,
	0xf3, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ConfessionClient is the client API for Confession service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ConfessionClient interface {
	HealthCheck(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HealthCheckReply, error)
}

type confessionClient struct {
	cc *grpc.ClientConn
}

func NewConfessionClient(cc *grpc.ClientConn) ConfessionClient {
	return &confessionClient{cc}
}

func (c *confessionClient) HealthCheck(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HealthCheckReply, error) {
	out := new(HealthCheckReply)
	err := c.cc.Invoke(ctx, "/confessionroom.Confession/HealthCheck", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConfessionServer is the server API for Confession service.
type ConfessionServer interface {
	HealthCheck(context.Context, *Empty) (*HealthCheckReply, error)
}

// UnimplementedConfessionServer can be embedded to have forward compatible implementations.
type UnimplementedConfessionServer struct {
}

func (*UnimplementedConfessionServer) HealthCheck(ctx context.Context, req *Empty) (*HealthCheckReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HealthCheck not implemented")
}

func RegisterConfessionServer(s *grpc.Server, srv ConfessionServer) {
	s.RegisterService(&_Confession_serviceDesc, srv)
}

func _Confession_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfessionServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/confessionroom.Confession/HealthCheck",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfessionServer).HealthCheck(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _Confession_serviceDesc = grpc.ServiceDesc{
	ServiceName: "confessionroom.Confession",
	HandlerType: (*ConfessionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HealthCheck",
			Handler:    _Confession_HealthCheck_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/confession.proto",
}
